# Even Fibonacci Numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89,...
# By considering the terms in the Fibonacci sequence whose
# value do not exceed four million, find the sum of the
# even-valued terms.

LIMIT = 4_000_000


def fib():
    sum = 0
    a = 0
    b = 1
    while b < LIMIT:
        if b % 2 == 0:
            sum += b
        a, b = b, a + b
    return sum


print(fib())
